---
abstract: 'flatten data structures using a template'
author:
  - 'Robert Rothenberg, C<< <rrwo at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Differences: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Struct-Flatten-Template
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 0
  Tie::RefHash: 0
  namespace::autoclean: 0
  perl: 5.8.0
  version: 0.77
resources:
  bugtracker: https://github.com/robrwo/Struct-Flatten-Template/issues
  homepage: http://rrwo.tumblr.com
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: git://github.com/robrwo/Struct-Flatten-Template.git
version: 0.001002
